name: Bug Report
about: Create a bug report for this library.
title: ''
labels: []
issue_body: true
body:
  - type: input
    attributes:
      label: What version of @tailwindcss/jit are you using?
      description: 'For example: v0.1.3'
    validations:
      required: true
  - type: input
    attributes:
      label: What version of Node.js are you using?
      description: 'For example: v12.0.0'
    validations:
      required: true
  - type: input
    attributes:
      label: What browser are you using?
      description: 'For example: Chrome, Safari, or N/A'
    validations:
      required: true
  - type: input
    attributes:
      label: What operating system are you using?
      description: 'For example: macOS, Windows'
    validations:
      required: true
  - type: input
    attributes:
      label: Reproduction repository
      description: A public GitHub repo that demonstrates the bug. Use "N/A" if you really think it's unnecessary.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Describe your issue below, including any important steps to reproduce and what behavior you expect.
